### ISSUE TITLE
This thermostat no longer compiles on latest HA

### ISSUE THREAD

**Issue by shoog03** [sballano/nspanel_thermostat#2]
This project no longer compiles within ESPHome on the latest versions of HomeAssistant.
It would be good if a note was added to the project to highlight this - or even better the project was updated or taken down.

Thanks

**Comment by sballano** [comment]
Thanks for letting me know it was not compiling, it is updated and will work with the last version.

Anyway, it's not a very nice thing to suggest to delete a project just because it is not helpful to you. I'm sure other people stumbled upon this before you and fixed the code themselves, saving a lot of time not having to write it from scratch

**Comment by shoog03** [comment]
Sorry for the tone. It has been a long day trying to get this working as a simple thermostat (not just this bit). I appreciate the prompt effort - but its still not completing as it wont upload the tft file.
